# Generated by Django 2.1.7 on 2019-03-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
