# Generated by Django 2.1.7 on 2019-03-26 15:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190326_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='articles/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='img/events/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='img/projects/'),
        ),
    ]
