# Generated by Django 2.1.7 on 2019-03-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190326_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['experience']},
        ),
    ]
