# Generated by Django 2.1.7 on 2019-03-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190329_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-experience']},
        ),
    ]
