# Generated by Django 2.1.7 on 2019-03-30 00:00

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190329_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='img/assets/'),
        ),
    ]
