# Generated by Django 2.1.7 on 2019-03-30 00:00

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_detail_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='img/events/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='img/projects/'),
        ),
    ]
