# Generated by Django 2.1.7 on 2019-04-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190406_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
    ]
