# Generated by Django 2.2 on 2019-04-25 02:15

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_article_latex_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='favicon',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='img/assets/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.CharField(default='', max_length=255),
        ),
    ]
